name: Deploy para o GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências
        run: npm ci

      - name: Compilar projeto (Build)
        env:
          NEXT_PUBLIC_SUPABASE_URL: "https://lqmuwffifroxlhqcogtt.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "sb_publishable_XfqKaavs6bpR9VDoot1XxA_kxeS46pk"
          NEXT_TELEMETRY_DISABLED: 1
        run: npx next build

      - name: Upload dos arquivos estáticos
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4